input {
  beats { port => 5044 type => "filebeat" }
  tcp { port => 5000 type => "syslog" codec => "json" }
}
filter {
  if [log_type] == "firewall" {
    grok { match => { "message" => "%{SYSLOGTIMESTAMP:timestamp} %{DATA:hostname} %{GREEDYDATA:log_msg}" } }
    date { match => [ "timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ] }
  }
  if [log_type] == "attack" {
    mutate {
      add_field => { "[@metadata][target_index]" => "waf-%{+YYYY.MM.dd}" }
    }
  }
  if [log_type] == "ids" {
    json { source => "message" target => "suricata" }
    mutate {
      add_field => { "[@metadata][target_index]" => "ids-%{+YYYY.MM.dd}" }
    }
  }
  if [log_type] == "firewall" or [log_type] == "iptables" {
    mutate {
      add_field => { "[@metadata][target_index]" => "filebeat-%{+YYYY.MM.dd}" }
    }
  }
  if ![[@metadata][target_index]] {
    mutate {
      add_field => { "[@metadata][target_index]" => "logstash-%{+YYYY.MM.dd}" }
    }
  }
}
output {
  elasticsearch { hosts => ["http://elasticsearch:9200"] index => "%{[@metadata][target_index]}" }
}
